PushTopic pushTopic = new PushTopic();
pushTopic.Name = 'ProjectUpdates';
pushTopic.Query = 'SELECT Id, Name, Description__c FROM Tasky_Project__c';
pushTopic.ApiVersion = 31.0;
pushTopic.NotifyForOperationCreate = true;
pushTopic.NotifyForOperationUpdate = true;
pushTopic.NotifyForOperationUndelete = true;
pushTopic.NotifyForOperationDelete = true;
pushTopic.NotifyForFields = 'Referenced';
insert pushTopic;